version: '3.8'

services:
  app:
    image: todo-front
    restart: always
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: todo-front
    environment:
      - REACT_APP_BACKEND_URL=http://nginx/api

  server:
    image: todo-backend
    restart: always
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    container_name: todo-backend
    environment:
      MONGO_URL: mongodb://mongo:27017/the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server

volumes:
  backend-data:
  mongo_data:
  redis_data:

